import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Gustavo Monteiro</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    <main>
      <section id="quem-sou">
        <h2>Olá :)</h2>
      </section>
    </main>

    </> 
  )
}
