import React, { useEffect } from "react";
import Head from "next/head";
import NavBar from "../src/Components/NavBar";
import Apresentation from "../src/Sections/Apresentation";
import { handleBgColor } from "../src/utils/scroll";
import About from "../src/Sections/About";
import Faco from "../src/../src/Sections/Faco";
import Trabalhos from "../src/Sections/Trabalhos";
import Conhecimentos from "../src/Sections/Conhecimentos";
import Contato from "../src/Sections/Contato";
import GlobalStyle from "../src/styles/GlobalStyle";

export default function Home({ about, servicos, projetos }) {
  useEffect(() => {
    window.onscroll = handleBgColor;
  }, []);
  const sectionLinks = [
    "Sobre mim",
    "O que faço",
    "Trabalhos",
    /*"Conhecimentos",*/ "Contato",
  ];
  return (
    <>
      <Head>
        <title>Gustavo Monteiro</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <GlobalStyle />
      <NavBar options={sectionLinks} />
      <Apresentation />
      <About content={about} />
      <Faco content={servicos} />
      <Trabalhos content={projetos} />
      {/* <Conhecimentos /> */}
      <Contato />
    </>
  );
}
export async function getStaticProps() {
  const token = process.env.NEXT_DATOCMS_API_TOKEN_RO;
  const resContent = await fetch("https://graphql.datocms.com/", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      query: `{ 
        about { sou, estudo }, 
        allServices {
          id,
          title,
          description
        },
        allProjects(
          orderBy: [createdAt_ASC]
        ){
          thumbnail{
            url,
            title
          }
          id,
          title,
          description,
          repoLink,
          linkProducao
        }
     }`,
    }),
  });
  const resContentJson = await resContent.json();
  const {
    about,
    ["allServices"]: servicos,
    ["allProjects"]: projetos,
  } = resContentJson.data;
  return {
    props: { about, servicos, projetos },
  };
}
