import Head from 'next/head'
import Apresentation from '../src/Sections/Apresentation'
import GlobalStyle from '../src/styles/GlobalStyle'

export default function Home() {
  return (
    <>
      <Head>
        <title>Gustavo Monteiro</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <GlobalStyle />
      <Apresentation />
    </> 
  )
}
